FROM python:3.10-slim

WORKDIR /app

# Установка зависимостей
COPY requirements.txt .
RUN pip install -r requirements.txt

# Копирование исходного кода
COPY main.py .
COPY fabric.py .
COPY publisher.py .
COPY strategy.py .
COPY strfabric.py .
COPY subscriber.py .
COPY test.py .
COPY fabrictest.py .
COPY strfabrictest.py .
COPY substest.py .

# Тесты запускаются в CI, не при сборке
CMD ["python", "-m", "pytest", "test.py"]