FROM python:3.10-slim

WORKDIR /app

# Установка зависимостей
COPY test_requirements.txt .
RUN pip install -r test_requirements.txt

# Копирование исходного кода
COPY main.py .
COPY fabric.py .
COPY publisher.py .
COPY strategy.py .
COPY strfabric.py .
COPY subscriber.py .
COPY test.py .
COPY fabrictest.py .
COPY strfabrictest.py .
COPY substest.py .

CMD ["python", "test.py"]